### ISSUE TITLE
Failure with SSL

### ISSUE THREAD

**Issue by jipiboily** [jipiboily/forwardlytics-ruby#6]
For some reason, it fails with SSL, at least, on Heroku.

`EOFError·end of file reached`

Stack trace:

```
vendor/ruby-2.2.3/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock': end of file reached (EOFError)
    from vendor/ruby-2.2.3/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
    from vendor/ruby-2.2.3/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
    from vendor/ruby-2.2.3/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
    from vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
    from vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
    from vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
    from vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
    from vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
    from vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1384:in `request'
    from vendor/bundle/ruby/2.2.0/gems/skylight-0.10.2/lib/skylight/probes/net_http.rb:34:in `block in request'
    from vendor/bundle/ruby/2.2.0/gems/skylight-0.10.2/lib/skylight/instrumenter.rb:197:in `instrument'
    from vendor/bundle/ruby/2.2.0/gems/skylight-0.10.2/lib/skylight/core.rb:108:in `instrument'
    from vendor/bundle/ruby/2.2.0/gems/skylight-0.10.2/lib/skylight/probes/net_http.rb:33:in `request'
    from vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
    from vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent.rb:431:in `disable_all_tracing'
    from vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
    from vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/cross_app_tracing.rb:41:in `tl_trace_http_request'
    from vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
    from vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
    from vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:853:in `start'
    from vendor/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
    from vendor/bundle/ruby/2.2.0/gems/skylight-0.10.2/lib/skylight/probes/net_http.rb:13:in `request'
    from vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
    from vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent.rb:431:in `disable_all_tracing'
    from vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
    from vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/cross_app_tracing.rb:48:in `tl_trace_http_request'
    from vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.2.312/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
    from vendor/bundle/ruby/2.2.0/bundler/gems/forwardlytics-ruby-32db83d20a18/lib/forwardlytics.rb:24:in `post'
    from vendor/bundle/ruby/2.2.0/bundler/gems/forwardlytics-ruby-32db83d20a18/lib/forwardlytics/track.rb:10:in `block in track'
```

**Comment by jipiboily** [comment]
It could actually be on the server side of Forwardlytics, not handling SSL properly.

**Comment by jipiboily** [comment]
Fixed by https://github.com/jipiboily/forwardlytics-ruby/commit/ea699d9f3ccb54a56180d136d9e9dba5c433ccad
